[package]
name = "synth_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-sync = "0.7.2"
fixed = "1.29.0"
defmt = "1.0.1"
midi = { path = "../midi" }

[dev-dependencies]
pretty_assertions = "1.4.1"
